trigger:
  branches:
    include:
      - main

variables:
  ACR_NAME: 'acrgrupo06'
  IMAGE_NAME: 'app-demo-grupo06'
  SERVICE_CONNECTION_NAME: 'acr-cnx-grupo6'

jobs:
  - job: 'BuildImageAndPushToACR'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          command: 'buildAndPush'
          containerRegistry: '$(SERVICE_CONNECTION_NAME)'
          repository: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME)'
          dockerfile: '**/Dockerfile'
          tags: |
            latest
        displayName: 'Build and Push Docker Image'